package com.lbthomas.healthcoach.core.sync.auth

import co.touchlab.kermit.Logger
import com.lbthomas.healthcoach.core.sync.adapters.GoogleDriveStorageAdapter
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.longOrNull
import java.awt.Desktop
import java.io.BufferedReader
import java.io.File
import java.io.InputStreamReader
import java.io.OutputStreamWriter
import java.net.InetAddress
import java.net.ServerSocket
import java.net.URI
import java.net.URLDecoder
import java.net.URLEncoder
import java.net.http.HttpClient
import java.net.http.HttpRequest
import java.net.http.HttpResponse
import java.security.MessageDigest
import java.security.SecureRandom
import java.time.Duration
import java.util.Base64
import java.util.Properties

actual object GoogleOAuthManager {

    private val json = Json {
        ignoreUnknownKeys = true
        isLenient = true
    }

    actual fun getResolvedClientId(): String {
        // 1. System property (override if specified at runtime)
        val sysProp = System.getProperty("google.clientId.desktop")?.trim()
        if (!sysProp.isNullOrBlank()) {
            Logger.d("GoogleOAuthManager: Using clientId from system property")
            return sysProp
        }

        // 2. Env variable (override if specified at runtime)
        val envProp = (System.getenv("GOOGLE_CLIENT_ID_DESKTOP") ?: System.getenv("google.clientId.desktop"))?.trim()
        if (!envProp.isNullOrBlank()) {
            Logger.d("GoogleOAuthManager: Using clientId from environment variable")
            return envProp
        }

        // 3. Build-injected constant generated by Gradle at build time
        if (GoogleAuthConfig.DESKTOP_CLIENT_ID.isNotBlank()) {
            Logger.d("GoogleOAuthManager: Using clientId from build-time GoogleAuthConfig")
            return GoogleAuthConfig.DESKTOP_CLIENT_ID
        }

        // 4. local.properties in working directory, parent, or user home (fallback)
        val searchDirs = listOf(
            File("."),
            File(System.getProperty("user.dir") ?: "."),
            File(System.getProperty("user.home") ?: "."),
            File(System.getProperty("user.home") ?: ".", ".healthcoach")
        )

        for (dir in searchDirs) {
            val localPropsFile = File(dir, "local.properties")
            if (localPropsFile.exists() && localPropsFile.isFile) {
                try {
                    val props = Properties()
                    localPropsFile.inputStream().use { props.load(it) }
                    val cid = props.getProperty("google.clientId.desktop")?.trim()
                    if (!cid.isNullOrBlank()) {
                        Logger.d("GoogleOAuthManager: Using clientId from local.properties in ${dir.absolutePath}")
                        return cid
                    }
                } catch (_: Exception) {}
            }
        }

        Logger.w("GoogleOAuthManager: Defaulting to built-in fallback clientId")
        return GoogleDriveStorageAdapter.DEFAULT_CLIENT_ID
    }

    actual fun getResolvedClientSecret(): String {
        // 1. System property (override if specified at runtime)
        val sysProp = System.getProperty("google.clientSecret.desktop")?.trim()
        if (!sysProp.isNullOrBlank()) {
            Logger.d("GoogleOAuthManager: Using clientSecret from system property")
            return sysProp
        }

        // 2. Env variable (override if specified at runtime)
        val envProp = (System.getenv("GOOGLE_CLIENT_SECRET_DESKTOP") ?: System.getenv("google.clientSecret.desktop"))?.trim()
        if (!envProp.isNullOrBlank()) {
            Logger.d("GoogleOAuthManager: Using clientSecret from environment variable")
            return envProp
        }

        // 3. Build-injected constant generated by Gradle at build time
        if (GoogleAuthConfig.DESKTOP_CLIENT_SECRET.isNotBlank()) {
            Logger.d("GoogleOAuthManager: Using clientSecret from build-time GoogleAuthConfig")
            return GoogleAuthConfig.DESKTOP_CLIENT_SECRET
        }

        // 4. local.properties in working directory, parent, or user home (fallback)
        val searchDirs = listOf(
            File("."),
            File(System.getProperty("user.dir") ?: "."),
            File(System.getProperty("user.home") ?: "."),
            File(System.getProperty("user.home") ?: ".", ".healthcoach")
        )

        for (dir in searchDirs) {
            val localPropsFile = File(dir, "local.properties")
            if (localPropsFile.exists() && localPropsFile.isFile) {
                try {
                    val props = Properties()
                    localPropsFile.inputStream().use { props.load(it) }
                    val secret = props.getProperty("google.clientSecret.desktop")?.trim()
                    if (!secret.isNullOrBlank()) {
                        Logger.d("GoogleOAuthManager: Using clientSecret from local.properties in ${dir.absolutePath}")
                        return secret
                    }
                } catch (_: Exception) {}
            }
        }

        return ""
    }

    private fun generateCodeVerifier(): String {
        val secureRandom = SecureRandom()
        val bytes = ByteArray(32)
        secureRandom.nextBytes(bytes)
        return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes)
    }

    private fun generateCodeChallenge(verifier: String): String {
        val bytes = verifier.toByteArray(Charsets.US_ASCII)
        val digest = MessageDigest.getInstance("SHA-256").digest(bytes)
        return Base64.getUrlEncoder().withoutPadding().encodeToString(digest)
    }

    private fun openBrowser(url: String) {
        if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
            Desktop.getDesktop().browse(URI(url))
        } else {
            val os = System.getProperty("os.name").lowercase()
            when {
                os.contains("linux") || os.contains("unix") -> Runtime.getRuntime().exec(arrayOf("xdg-open", url))
                os.contains("mac") -> Runtime.getRuntime().exec(arrayOf("open", url))
                os.contains("win") -> Runtime.getRuntime().exec(arrayOf("cmd", "/c", "start", url))
                else -> throw UnsupportedOperationException("Cannot open browser automatically. Please open this URL: $url")
            }
        }
    }

    actual suspend fun authorize(clientId: String): Result<GoogleAuthSession> = withContext(Dispatchers.IO) {
        var serverSocket: ServerSocket? = null
        try {
            val effectiveClientId = if (clientId.isNotBlank()) clientId else getResolvedClientId()
            val verifier = generateCodeVerifier()
            val challenge = generateCodeChallenge(verifier)

            serverSocket = ServerSocket(0, 1, InetAddress.getByName("127.0.0.1"))
            val port = serverSocket.localPort
            val redirectUri = "http://127.0.0.1:$port"

            Logger.i("Google OAuth: Initializing PKCE authorization flow on loopback redirect: $redirectUri")

            val scope = "https://www.googleapis.com/auth/drive.appdata https://www.googleapis.com/auth/userinfo.email openid"
            val authUrl = "https://accounts.google.com/o/oauth2/v2/auth?" +
                    "client_id=" + URLEncoder.encode(effectiveClientId, "UTF-8") +
                    "&redirect_uri=" + URLEncoder.encode(redirectUri, "UTF-8") +
                    "&response_type=code" +
                    "&scope=" + URLEncoder.encode(scope, "UTF-8") +
                    "&code_challenge=" + URLEncoder.encode(challenge, "UTF-8") +
                    "&code_challenge_method=S256" +
                    "&access_type=offline" +
                    "&prompt=consent"

            Logger.i("Google OAuth: Opening browser for authentication...")
            Logger.d("Google OAuth: Authorization URL: $authUrl")

            try {
                openBrowser(authUrl)
            } catch (e: Exception) {
                serverSocket.close()
                Logger.e("Google OAuth: Failed to open system browser", e)
                return@withContext Result.failure(Exception("Could not open browser for authorization: ${e.message}\nPlease open this URL manually: $authUrl", e))
            }

            Logger.d("Google OAuth: Waiting up to 120s for loopback callback on port $port...")
            serverSocket.soTimeout = 120_000 // 2 minutes
            val socket = try {
                serverSocket.accept()
            } catch (e: Exception) {
                serverSocket.close()
                Logger.e("Google OAuth: Timeout or error waiting for browser response", e)
                return@withContext Result.failure(Exception("Authorization timed out waiting for browser login", e))
            }

            var authCode: String? = null
            var authError: String? = null

            socket.use { s ->
                val reader = BufferedReader(InputStreamReader(s.getInputStream(), Charsets.UTF_8))
                val firstLine = reader.readLine() ?: ""
                Logger.d("Google OAuth: Received loopback request: $firstLine")

                val uriPart = firstLine.split(" ").getOrNull(1) ?: ""
                if (uriPart.contains("?")) {
                    val query = uriPart.substringAfter("?")
                    val queryParams = query.split("&").associate { param ->
                        val parts = param.split("=", limit = 2)
                        URLDecoder.decode(parts[0], "UTF-8") to (if (parts.size > 1) URLDecoder.decode(parts[1], "UTF-8") else "")
                    }
                    authCode = queryParams["code"]
                    authError = queryParams["error"]
                }

                val responseBody = if (authCode != null) {
                    """
                    <!DOCTYPE html>
                    <html>
                    <head>
                        <meta charset="utf-8">
                        <title>HealthCoach - Authorization Successful</title>
                        <style>
                            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; display: flex; align-items: center; justify-content: center; height: 100vh; margin: 0; background-color: #f8fafc; color: #1e293b; }
                            .card { background: white; padding: 2.5rem; border-radius: 12px; box-shadow: 0 10px 15px -3px rgba(0,0,0,0.1); text-align: center; max-width: 440px; }
                            h1 { color: #16a34a; font-size: 1.5rem; margin-top: 0; }
                            p { color: #64748b; font-size: 0.95rem; line-height: 1.5; }
                        </style>
                    </head>
                    <body>
                        <div class="card">
                            <h1>Authorization Successful!</h1>
                            <p>HealthCoach has successfully connected to your Google account.</p>
                            <p>You can close this browser tab and return to HealthCoach.</p>
                        </div>
                    </body>
                    </html>
                    """.trimIndent()
                } else {
                    """
                    <!DOCTYPE html>
                    <html>
                    <head>
                        <meta charset="utf-8">
                        <title>HealthCoach - Authorization Failed</title>
                        <style>
                            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; display: flex; align-items: center; justify-content: center; height: 100vh; margin: 0; background-color: #f8fafc; color: #1e293b; }
                            .card { background: white; padding: 2.5rem; border-radius: 12px; box-shadow: 0 10px 15px -3px rgba(0,0,0,0.1); text-align: center; max-width: 440px; }
                            h1 { color: #dc2626; font-size: 1.5rem; margin-top: 0; }
                            p { color: #64748b; font-size: 0.95rem; line-height: 1.5; }
                        </style>
                    </head>
                    <body>
                        <div class="card">
                            <h1>Authorization Failed</h1>
                            <p>${authError ?: "No authorization code was received."}</p>
                            <p>Please return to the application and try again.</p>
                        </div>
                    </body>
                    </html>
                    """.trimIndent()
                }

                val out = OutputStreamWriter(s.getOutputStream(), Charsets.UTF_8)
                val statusLine = if (authCode != null) "HTTP/1.1 200 OK" else "HTTP/1.1 400 Bad Request"
                val bodyBytes = responseBody.toByteArray(Charsets.UTF_8)
                out.write("$statusLine\r\n")
                out.write("Content-Type: text/html; charset=utf-8\r\n")
                out.write("Content-Length: ${bodyBytes.size}\r\n")
                out.write("Connection: close\r\n\r\n")
                out.write(responseBody)
                out.flush()
            }

            serverSocket.close()

            if (authCode.isNullOrBlank()) {
                Logger.e("Google OAuth: Authorization failed - no code received: $authError")
                return@withContext Result.failure(Exception("Google authorization failed: ${authError ?: "No authorization code received"}"))
            }

            Logger.i("Google OAuth: Authorization code received. Proceeding to exchange for tokens...")
            exchangeCodeForToken(effectiveClientId, authCode, verifier, redirectUri)
        } catch (e: Exception) {
            serverSocket?.close()
            Logger.e("Google OAuth: Authorization flow encountered an error", e)
            Result.failure(e)
        }
    }

    private suspend fun exchangeCodeForToken(
        clientId: String,
        code: String,
        codeVerifier: String,
        redirectUri: String
    ): Result<GoogleAuthSession> = withContext(Dispatchers.IO) {
        try {
            val client = HttpClient.newBuilder()
                .connectTimeout(Duration.ofSeconds(15))
                .build()

            val effectiveClientSecret = getResolvedClientSecret()
            var postParams = "client_id=" + URLEncoder.encode(clientId, "UTF-8") +
                    "&code=" + URLEncoder.encode(code, "UTF-8") +
                    "&code_verifier=" + URLEncoder.encode(codeVerifier, "UTF-8") +
                    "&grant_type=authorization_code" +
                    "&redirect_uri=" + URLEncoder.encode(redirectUri, "UTF-8")

            if (effectiveClientSecret.isNotBlank()) {
                Logger.d("Google OAuth: Including client_secret in token exchange request")
                postParams += "&client_secret=" + URLEncoder.encode(effectiveClientSecret, "UTF-8")
            } else {
                Logger.d("Google OAuth: No client_secret configured for token exchange")
            }

            Logger.i("Google OAuth: Sending POST request to https://oauth2.googleapis.com/token...")
            val request = HttpRequest.newBuilder()
                .uri(URI.create("https://oauth2.googleapis.com/token"))
                .header("Content-Type", "application/x-www-form-urlencoded")
                .timeout(Duration.ofSeconds(20))
                .POST(HttpRequest.BodyPublishers.ofString(postParams))
                .build()

            val response = client.send(request, HttpResponse.BodyHandlers.ofString())
            Logger.d("Google OAuth: Token endpoint responded with HTTP ${response.statusCode()}")

            if (response.statusCode() !in 200..299) {
                Logger.e("Google OAuth: Token exchange error body: ${response.body()}")
                val errorJson = runCatching { json.parseToJsonElement(response.body()).jsonObject }.getOrNull()
                val errorDesc = errorJson?.get("error_description")?.jsonPrimitive?.content
                    ?: errorJson?.get("error")?.jsonPrimitive?.content
                    ?: "HTTP ${response.statusCode()}: ${response.body()}"
                return@withContext Result.failure(Exception("Token exchange failed: $errorDesc"))
            }

            val bodyJson = json.parseToJsonElement(response.body()).jsonObject
            val accessToken = bodyJson["access_token"]?.jsonPrimitive?.content
                ?: return@withContext Result.failure(Exception("No access_token returned by Google"))
            val refreshToken = bodyJson["refresh_token"]?.jsonPrimitive?.content ?: ""
            val expiresIn = bodyJson["expires_in"]?.jsonPrimitive?.longOrNull

            var email = ""
            val idToken = bodyJson["id_token"]?.jsonPrimitive?.content
            if (!idToken.isNullOrBlank()) {
                email = extractEmailFromIdToken(idToken)
            }
            if (email.isBlank()) {
                email = fetchUserEmail(accessToken)
            }

            Logger.i("Google OAuth: Token exchange succeeded. Account: $email, expiresIn: ${expiresIn}s, hasRefreshToken: ${refreshToken.isNotBlank()}")

            Result.success(
                GoogleAuthSession(
                    accessToken = accessToken,
                    refreshToken = refreshToken,
                    email = email,
                    expiresInSeconds = expiresIn
                )
            )
        } catch (e: Exception) {
            Logger.e("Google OAuth: Token exchange exception: ${e.message}", e)
            Result.failure(e)
        }
    }

    private fun extractEmailFromIdToken(idToken: String): String {
        return try {
            val parts = idToken.split(".")
            if (parts.size >= 2) {
                val payloadBytes = Base64.getUrlDecoder().decode(parts[1])
                val payloadStr = String(payloadBytes, Charsets.UTF_8)
                val bodyJson = json.parseToJsonElement(payloadStr).jsonObject
                bodyJson["email"]?.jsonPrimitive?.content ?: ""
            } else ""
        } catch (_: Exception) {
            ""
        }
    }

    private suspend fun fetchUserEmail(accessToken: String): String = withContext(Dispatchers.IO) {
        try {
            Logger.d("Google OAuth: Fetching user info from https://www.googleapis.com/oauth2/v3/userinfo...")
            val client = HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(10)).build()
            val request = HttpRequest.newBuilder()
                .uri(URI.create("https://www.googleapis.com/oauth2/v3/userinfo"))
                .header("Authorization", "Bearer $accessToken")
                .timeout(Duration.ofSeconds(10))
                .GET()
                .build()
            val response = client.send(request, HttpResponse.BodyHandlers.ofString())
            if (response.statusCode() == 200) {
                val bodyJson = json.parseToJsonElement(response.body()).jsonObject
                val email = bodyJson["email"]?.jsonPrimitive?.content ?: ""
                Logger.d("Google OAuth: Retrieved user email: $email")
                email
            } else {
                Logger.w("Google OAuth: Userinfo endpoint responded with HTTP ${response.statusCode()}: ${response.body()}")
                ""
            }
        } catch (e: Exception) {
            Logger.w("Google OAuth: Failed to fetch userinfo: ${e.message}")
            ""
        }
    }

    actual suspend fun validateToken(
        accessToken: String,
        refreshToken: String,
        clientId: String
    ): Result<GoogleTokenValidationResult> = withContext(Dispatchers.IO) {
        if (accessToken.isBlank()) {
            Logger.d("Google OAuth: Validation requested with empty access token")
            return@withContext Result.success(
                GoogleTokenValidationResult(
                    isValid = false,
                    errorMessage = "No access token present. Click Authorize to connect."
                )
            )
        }

        try {
            Logger.i("Google OAuth: Validating token at https://oauth2.googleapis.com/tokeninfo...")
            val client = HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(10)).build()
            val request = HttpRequest.newBuilder()
                .uri(URI.create("https://oauth2.googleapis.com/tokeninfo?access_token=" + URLEncoder.encode(accessToken, "UTF-8")))
                .timeout(Duration.ofSeconds(15))
                .GET()
                .build()

            val response = client.send(request, HttpResponse.BodyHandlers.ofString())
            Logger.d("Google OAuth: Tokeninfo responded with HTTP ${response.statusCode()}")

            if (response.statusCode() == 200) {
                val bodyJson = json.parseToJsonElement(response.body()).jsonObject
                val email = bodyJson["email"]?.jsonPrimitive?.content
                val expiresIn = bodyJson["expires_in"]?.jsonPrimitive?.longOrNull
                val scopeStr = bodyJson["scope"]?.jsonPrimitive?.content ?: ""
                val scopes = scopeStr.split(" ").filter { it.isNotBlank() }
                Logger.i("Google OAuth: Token is valid. Email: $email, expiresIn: ${expiresIn}s, scopes: $scopes")
                Result.success(
                    GoogleTokenValidationResult(
                        isValid = true,
                        email = email,
                        expiresInSeconds = expiresIn,
                        scopes = scopes
                    )
                )
            } else {
                Logger.w("Google OAuth: Tokeninfo reported invalid/expired token (HTTP ${response.statusCode()}): ${response.body()}")

                // If token has expired or is invalid, try refresh token if present
                if (refreshToken.isNotBlank()) {
                    Logger.i("Google OAuth: Attempting token refresh using stored refresh token...")
                    val effectiveClientId = if (clientId.isNotBlank()) clientId else getResolvedClientId()
                    val refreshResult = refreshAccessToken(effectiveClientId, refreshToken)
                    if (refreshResult.isSuccess) {
                        val newSession = refreshResult.getOrThrow()
                        Logger.i("Google OAuth: Token refreshed successfully. New access token acquired for ${newSession.email}")
                        return@withContext Result.success(
                            GoogleTokenValidationResult(
                                isValid = true,
                                email = newSession.email,
                                expiresInSeconds = newSession.expiresInSeconds,
                                newAccessToken = newSession.accessToken
                            )
                        )
                    } else {
                        Logger.w("Google OAuth: Automatic token refresh failed: ${refreshResult.exceptionOrNull()?.message}")
                    }
                }

                val errorJson = runCatching { json.parseToJsonElement(response.body()).jsonObject }.getOrNull()
                val errorMsg = errorJson?.get("error_description")?.jsonPrimitive?.content
                    ?: errorJson?.get("error")?.jsonPrimitive?.content
                    ?: "Access token is invalid or expired (HTTP ${response.statusCode()})"
                Result.success(
                    GoogleTokenValidationResult(
                        isValid = false,
                        errorMessage = errorMsg
                    )
                )
            }
        } catch (e: Exception) {
            Logger.e("Google OAuth: Token validation exception: ${e.message}", e)
            Result.failure(e)
        }
    }

    actual suspend fun refreshAccessToken(
        clientId: String,
        refreshToken: String
    ): Result<GoogleAuthSession> = withContext(Dispatchers.IO) {
        if (refreshToken.isBlank()) {
            Logger.w("Google OAuth: Refresh called with blank refresh token")
            return@withContext Result.failure(IllegalArgumentException("No refresh token available"))
        }

        try {
            val client = HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(10)).build()
            val effectiveClientId = if (clientId.isNotBlank()) clientId else getResolvedClientId()
            val effectiveClientSecret = getResolvedClientSecret()

            var postParams = "client_id=" + URLEncoder.encode(effectiveClientId, "UTF-8") +
                    "&refresh_token=" + URLEncoder.encode(refreshToken, "UTF-8") +
                    "&grant_type=refresh_token"

            if (effectiveClientSecret.isNotBlank()) {
                Logger.d("Google OAuth: Including client_secret in token refresh request")
                postParams += "&client_secret=" + URLEncoder.encode(effectiveClientSecret, "UTF-8")
            } else {
                Logger.d("Google OAuth: No client_secret configured for token refresh")
            }

            Logger.i("Google OAuth: Sending token refresh request to https://oauth2.googleapis.com/token...")
            val request = HttpRequest.newBuilder()
                .uri(URI.create("https://oauth2.googleapis.com/token"))
                .header("Content-Type", "application/x-www-form-urlencoded")
                .timeout(Duration.ofSeconds(15))
                .POST(HttpRequest.BodyPublishers.ofString(postParams))
                .build()

            val response = client.send(request, HttpResponse.BodyHandlers.ofString())
            Logger.d("Google OAuth: Token refresh response HTTP ${response.statusCode()}")

            if (response.statusCode() in 200..299) {
                val bodyJson = json.parseToJsonElement(response.body()).jsonObject
                val newAccessToken = bodyJson["access_token"]?.jsonPrimitive?.content ?: ""
                val expiresIn = bodyJson["expires_in"]?.jsonPrimitive?.longOrNull
                var email = ""
                val idToken = bodyJson["id_token"]?.jsonPrimitive?.content
                if (!idToken.isNullOrBlank()) {
                    email = extractEmailFromIdToken(idToken)
                }
                if (email.isBlank() && newAccessToken.isNotBlank()) {
                    email = fetchUserEmail(newAccessToken)
                }
                Logger.i("Google OAuth: Token refreshed successfully. Email: $email, expiresIn: ${expiresIn}s")
                Result.success(
                    GoogleAuthSession(
                        accessToken = newAccessToken,
                        refreshToken = refreshToken,
                        email = email,
                        expiresInSeconds = expiresIn
                    )
                )
            } else {
                Logger.e("Google OAuth: Token refresh failed (HTTP ${response.statusCode()}): ${response.body()}")
                val errorJson = runCatching { json.parseToJsonElement(response.body()).jsonObject }.getOrNull()
                val errorDesc = errorJson?.get("error_description")?.jsonPrimitive?.content
                    ?: errorJson?.get("error")?.jsonPrimitive?.content
                    ?: "HTTP ${response.statusCode()}"
                Result.failure(Exception("Token refresh failed: $errorDesc"))
            }
        } catch (e: Exception) {
            Logger.e("Google OAuth: Exception during token refresh: ${e.message}", e)
            Result.failure(e)
        }
    }

    actual suspend fun revokeToken(token: String): Result<Unit> = withContext(Dispatchers.IO) {
        if (token.isBlank()) {
            Logger.d("Google OAuth: Revoke called with blank token")
            return@withContext Result.success(Unit)
        }
        try {
            Logger.i("Google OAuth: Revoking token at https://oauth2.googleapis.com/revoke...")
            val client = HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(10)).build()
            val postParams = "token=" + URLEncoder.encode(token, "UTF-8")
            val request = HttpRequest.newBuilder()
                .uri(URI.create("https://oauth2.googleapis.com/revoke"))
                .header("Content-Type", "application/x-www-form-urlencoded")
                .timeout(Duration.ofSeconds(15))
                .POST(HttpRequest.BodyPublishers.ofString(postParams))
                .build()

            val response = client.send(request, HttpResponse.BodyHandlers.ofString())
            Logger.i("Google OAuth: Token revoke completed with HTTP ${response.statusCode()}")
            Result.success(Unit)
        } catch (e: Exception) {
            Logger.w("Google OAuth: Error while revoking token: ${e.message}")
            Result.success(Unit)
        }
    }
}
