import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.util.Properties

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidMultiplatformLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)

    alias(libs.plugins.kotlinx.serialization)
    alias(libs.plugins.sqldelight)
}

sqldelight {
    databases {
        create("Database") {
            packageName.set("com.lbthomas.healthcoach")
            dialect(libs.sqldelight.sqlite.dialect.get().toString())

            // output directory for generated migration schema
            schemaOutputDirectory = file("src/commonMain/sqldelight/migrations")
            // execute `gradlew generateCommonMainDatabaseSchema` to generate the current db schema, before making a migration
            verifyMigrations = true
        }
    }
}

kotlin {
    compilerOptions {
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    jvm()
    
    android {
       namespace = "com.lbthomas.healthcoach.shared"
       compileSdk = libs.versions.android.compileSdk.get().toInt()
       minSdk = libs.versions.android.minSdk.get().toInt()
    
       compilerOptions {
           jvmTarget = JvmTarget.JVM_11
       }
       androidResources {
           enable = true
       }
       withHostTest {
           isIncludeAndroidResources = true
       }
       withDeviceTestBuilder {
           sourceSetTreeName = "test"
       }.configure {
           instrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
       }
    }
    
    val generatedGoogleAuthDir = layout.buildDirectory.dir("generated/source/googleAuth/commonMain/kotlin")

    val generateGoogleAuthConfig = tasks.register("generateGoogleAuthConfig") {
        val desktopClientIdProvider = providers.provider {
            findProperty("google.clientId.desktop") as? String
                ?: System.getenv("GOOGLE_CLIENT_ID_DESKTOP")
                ?: System.getenv("google.clientId.desktop")
                ?: run {
                    val localPropsFile = rootProject.file("local.properties")
                    if (localPropsFile.exists()) {
                        val props = Properties()
                        localPropsFile.inputStream().use { props.load(it) }
                        props.getProperty("google.clientId.desktop")
                    } else null
                }
                ?: ""
        }

        val desktopClientSecretProvider = providers.provider {
            findProperty("google.clientSecret.desktop") as? String
                ?: System.getenv("GOOGLE_CLIENT_SECRET_DESKTOP")
                ?: System.getenv("google.clientSecret.desktop")
                ?: run {
                    val localPropsFile = rootProject.file("local.properties")
                    if (localPropsFile.exists()) {
                        val props = Properties()
                        localPropsFile.inputStream().use { props.load(it) }
                        props.getProperty("google.clientSecret.desktop")
                    } else null
                }
                ?: ""
        }

        val androidClientIdProvider = providers.provider {
            findProperty("google.clientId.android") as? String
                ?: System.getenv("GOOGLE_CLIENT_ID_ANDROID")
                ?: System.getenv("google.clientId.android")
                ?: run {
                    val localPropsFile = rootProject.file("local.properties")
                    if (localPropsFile.exists()) {
                        val props = Properties()
                        localPropsFile.inputStream().use { props.load(it) }
                        props.getProperty("google.clientId.android")
                    } else null
                }
                ?: "dummy-android-client-id.apps.googleusercontent.com"
        }

        inputs.property("desktopClientId", desktopClientIdProvider)
        inputs.property("desktopClientSecret", desktopClientSecretProvider)
        inputs.property("androidClientId", androidClientIdProvider)
        outputs.dir(generatedGoogleAuthDir)

        doLast {
            val desktopId = desktopClientIdProvider.get().trim()
            val desktopSecret = desktopClientSecretProvider.get().trim()
            val androidId = androidClientIdProvider.get().trim()
            val outputFile = generatedGoogleAuthDir.get().asFile.resolve("com/lbthomas/healthcoach/core/sync/auth/GoogleAuthConfig.kt")
            outputFile.parentFile.mkdirs()
            outputFile.writeText(
                """
                package com.lbthomas.healthcoach.core.sync.auth

                /**
                 * Generated by Gradle at build time.
                 * Embeds Google OAuth Client IDs and Desktop Client Secret directly into the compiled binary.
                 */
                internal object GoogleAuthConfig {
                    const val DESKTOP_CLIENT_ID: String = "$desktopId"
                    const val DESKTOP_CLIENT_SECRET: String = "$desktopSecret"
                    const val ANDROID_CLIENT_ID: String = "$androidId"
                }
                """.trimIndent() + "\n"
            )
        }
    }

    sourceSets {
        commonMain.configure {
            kotlin.srcDir(generateGoogleAuthConfig)
        }
        jvmMain.dependencies {
            implementation(libs.sqldelight.sqlite.driver)
            implementation(libs.slf4j)
        }
        androidMain.dependencies {
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.compose.uiTooling)
            implementation(libs.androidx.activity.compose)
            implementation(libs.sqldelight.android.driver)
            implementation(libs.koin.android)
        }
        commonMain.dependencies {
            api(libs.kotlinx.coroutines.core)
            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.material3)
            implementation(libs.compose.ui)
            implementation(libs.compose.components.resources)
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodelCompose)
            implementation(libs.androidx.lifecycle.runtimeCompose)

            implementation(libs.bundles.koin)
            implementation(libs.compose.material.icons.extended)
            implementation(libs.kermit)
            implementation(libs.koin.core)
            implementation(libs.kotlinx.datetime)
            implementation(libs.kotlinx.serialization)
            implementation(libs.sqldelight.coroutines.extensions)
            implementation(libs.vico.compose)
            implementation(libs.vico.compose.m3)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
    }
}

compose.resources {
    publicResClass = true
}

dependencies {
    androidRuntimeClasspath(libs.compose.uiTooling)
}